[WIP] CMS-42 Provide translation support for Stories, Features, Statistics, Headers, Roadmap Iterations
ChronoBank/io.chronobank.web pull request #7
Opened 2018-02-08 15:46 UTC by ex1st0r

2018-02-14 11:21 UTC, ipavlenko requested changes

2018-02-14 11:21 UTC, ipavlenko commented on pages/faq.js
> +    await store.dispatch(setUserLanguages(req && req.headers && req.headers['accept-language']))
Send req.headers to setUserLanguages, it should also check Cookies in the future.

2018-02-14 11:21 UTC, ipavlenko commented on src/models/lib/HeaderModel.js
> +      brief: localeModelFields && 'brief' in localeModelFields ? localeModelFields.brief : data.brief ,
Did you forget (-brackets-) for 'brief' in localeModelFields ?

2018-02-14 11:21 UTC, ipavlenko commented on src/models/lib/IterationModel.js
>        title: data.title,
Localize title

2018-02-14 11:21 UTC, ipavlenko commented on src/models/lib/StatisticModel.js
>        title: data.title,
Localize title

2018-02-14 11:21 UTC, ipavlenko commented on src/models/lib/StoryModel.js
>        title: data.title,
Localize title

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/actions.js
> +    features: data.features.map((feature) => FeatureModel.fromServerModel(feature, { locales }))
Maybe it is better to find best locale here and pass only the best locale down to the fromServerModel method?

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/actions.js
> +    statistics: data.statistics.map((statistic) => StatisticModel.fromServerModel(statistic, { locales }))
See comments above

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/actions.js
> +    headers: data.headers.map((header) => HeaderModel.fromServerModel(header, { locales }))
See comments above

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/actions.js
> +    stories: data.stories.map((story) => StoryModel.fromServerModel(story, { locales }))
See comments above

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/actions.js
> +    iterations: data.iterations.map((iteration) => IterationModel.fromServerModel(iteration, { locales }))
See comments above

2018-02-14 11:21 UTC, ipavlenko commented on src/store/lib/pages/reducer.js
> +  userLocales: ''
Maybe it is better to store best locale here?

2018-02-15 10:16 UTC, ex1st0r commented on src/store/lib/pages/actions.js
> +    features: data.features.map((feature) => FeatureModel.fromServerModel(feature, { locales }))
We need list of locales for identify user language, but it individual for every model.

2018-02-15 11:38 UTC, ex1st0r commented on src/models/lib/HeaderModel.js
> +      brief: localeModelFields && 'brief' in localeModelFields ? localeModelFields.brief : data.brief ,
it's not necessary

2018-02-15 11:44 UTC, ex1st0r commented on src/store/lib/pages/reducer.js
> +  userLocales: ''
see above

2018-02-16 13:56 UTC, merged